-- PAIR take-home exercise: Content assembly + progress
-- Schema: PostgreSQL 14+ (works on 13+ too)
-- Notes:
-- - IDs are integers for simplicity.
-- - Blocks are "global" building blocks; block_variants can override per tenant.
-- - Progress is tracked per user+lesson+block, with a monotonic status (seen -> completed).

CREATE TABLE tenants (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL
);

CREATE TABLE users (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id    INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email        TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, email)
);

CREATE TABLE lessons (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id    INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  slug         TEXT NOT NULL,
  title        TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, slug)
);

CREATE TABLE blocks (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_type   TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The ordered list of blocks inside a lesson.
CREATE TABLE lesson_blocks (
  lesson_id    INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  block_id     INTEGER NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
  position     INTEGER NOT NULL,
  PRIMARY KEY (lesson_id, block_id),
  UNIQUE (lesson_id, position)
);

-- Variant data for a block.
-- If tenant_id IS NULL => default variant.
-- If tenant_id is set => tenant-specific override for that block.
CREATE TABLE block_variants (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id     INTEGER NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
  tenant_id    INTEGER REFERENCES tenants(id) ON DELETE CASCADE,
  data         JSONB NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (block_id, tenant_id)
);

-- User progress per block (monotonic): 'seen' < 'completed'
CREATE TABLE user_block_progress (
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id    INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  block_id     INTEGER NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
  status       TEXT NOT NULL CHECK (status IN ('seen', 'completed')),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id, block_id)
);

-- Helpful indexes (not exhaustive; candidates may propose more)
CREATE INDEX idx_users_tenant_id ON users(tenant_id);
CREATE INDEX idx_lessons_tenant_id ON lessons(tenant_id);
CREATE INDEX idx_lesson_blocks_lesson_pos ON lesson_blocks(lesson_id, position);
CREATE INDEX idx_block_variants_block_tenant ON block_variants(block_id, tenant_id);
CREATE INDEX idx_user_block_progress_user_lesson ON user_block_progress(user_id, lesson_id);
