# Generated by Django 4.2.28 on 2026-02-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_type', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockVariant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'block_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lesson_blocks', serialize=False, to='lessons.block')),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'lesson_blocks',
                'ordering': ['position'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBlockProgress',
            fields=[
                ('block', models.ForeignKey(db_column='block_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='lessons.block')),
                ('status', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_block_progress',
                'managed': False,
            },
        ),
    ]
